name: PR Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run tests
        run: ./gradlew test
  publish:
    name: Check that the publish plugin works
    runs-on: ubuntu-latest
    needs: [tests, lint]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check that the publish plugin works
        run: ./gradlew publishToMavenLocal
  lint:
    name: Check that the code is formatted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check that the code is formatted
        run: ./gradlew spotlessCheck
